// <auto-generated />
namespace ReksadanaRekon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFKBank_Retur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFKBank_Retur));
        
        string IMigrationMetadata.Id
        {
            get { return "202104101326347_AddFKBank_Retur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
