// <auto-generated />
namespace ReksadanaRekon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRed_Swi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRed_Swi));
        
        string IMigrationMetadata.Id
        {
            get { return "202103220629079_AddRed_Swi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
